### ISSUE TITLE
`gatorgrade` check incorrect

### ISSUE THREAD

**Issue by dluman** [term-world/garage-solution#14]
We need to fix the grader check that looks at the `.junk` files. This works:

```yaml
- description: The Groomba cleaned up the garage and removed all .junk files
  category: Reclaiming the garage
  check: MatchCommandFragment
  options:
    fragment: "0"
    count: 1
    command: ls -l workshop | grep ".junk" | wc -l
```
